### PR TITLE
Remove attempting to edit database for invalid data

### PR DESCRIPTION
**Pull request by Sammidysam**
The code is a little repetitive and it would be good to check both in clear messages and import messages, but I just wanted to prevent us from trying to edit the database when someone imports something like an image file.

### CODE REVIEW

**Review by adartulloch — COMMENTED** [review]
This looks good! I'll test with some invalid data and check what responses I get.

**Review by adartulloch — COMMENTED** [review]
Is there any way to check directly for the file extension? If we know we are only accepting .csv files currently, could we maybe try implementing something like this https://stackoverflow.com/questions/7977084/check-file-type-when-form-submit , where we maybe make a `fileExtension` array with `['csv']` as an entry, and check the filepath. As an addition to this, we could maybe deal with this in the React frontend, and have the upload dialogue only allow .csv documents to be selected when a user browses through files. Obviously, still validating the data by the backend is necessary, but that could be a nice UI addition to make it clear to the user that only .csv files are what we process.  Either way, I still really like this code because it handles files that _are_ .csv files but still aren't formatted according to the protocol that we're using.

**Comment by Sammidysam** [comment]
Thanks so much for the feedback!  I don't know if I want to necessarily commit to `csv` or `tsv` files at the current time, but this is a wonderful idea for the future.  @rehannan Can you look it over and add it to your future feature list if you'd like?

I'll merge this in the meantime - the idea would be implemented in `cwd-editor` anyhow.

**Comment by rehannan** [comment]
@adartulloch I think that's a great idea and definitely good practice for frontend UI. However, I don't think at the moment it is the biggest priority seeing as it will be a while yet before we have people outside of ED uploading and I think a simple written instruction could take care of this for now. I will add it to the future feature list with that link, though. Nice!

**Pull request merged**
