### PR TITLE
delete route through backend

### PR DESCRIPTION
**Pull request by adartulloch**
This PR is aimed towards creating a delete route for messages, complementary towards the frontend. I'm not quite sure if the `router.post` params are correct. Otherwise, what I do is create a `const query` that should ID the message that we want to delete, then I use `db.collections.deleteOne` with that query.

### CODE REVIEW

**Review by Sammidysam — CHANGES_REQUESTED** [review]
I did not truly test this, but I am worried about it working right.  Here are my concerns:
1. `/:_id/messages/:delete` means that both the `_id` will become `req.params._id` and `delete` will become `req.params.delete`.  So, you could go to `/55/messages/5` and it would mean delete.  This is confusing and I do not really think this is desired.
1. The first argument to a router method will be a Request object, and the second argument will be a Response object.  This is very confusing to rename the Request to be `id` and the Response to be `path`.  Look up Express.js if you are unfamiliar with the structure here and would like more information (I think our code is generally clear enough though that this code is good reference code).
1. I do not think you can create a new `ObjectId` from a `Request` object.
1. I have no idea what a `Response` object will transform to as a string in making it an object key.
1. What is `itemsCollection`?  I never knew it was defined anywhere.
1. I think this code has a syntax error.  The callback for `post` should be an argument to it - instead, it is passed as another entity after a comma.  Did this yield a syntax error for you?
1. I think that we need a different route for both a gauge message delete and a view message delete.  I don't think we can create a function that will magically do both, but maybe I'm wrong.

**Comment by adartulloch** [comment]
Yes, I realized there are numerous errors in this, and I'm rewriting this route by using `router.delete`. I had written this code without proper knowledge of Express.js so I spend quite a bit of time looking up how routing operates. I do want to respond to your third concern: based on previous routes written in this file, it seems like making an `ObjectID` from a `req` seems to be possible (the statement `"_id" : new ObjectId(req.params_id)` appears multiple times). Which seems to make sense if the goal is to locate that specific `id` in the database and perform some action on it. Unless I am still misunderstanding? I'd like to know what you think.

**Comment by Sammidysam** [comment]
I would probably make it a POST route.  And yes, you will create an ObjectID from the request with `new ObjectId(req.params_id)`.  I think I was just saying that you were passing in `req` itself into the ObjectID creation, which won't work, unfortunately.

We can talk through this if it would help.

**Review by Sammidysam — CHANGES_REQUESTED** [review]
Just about there!  Honestly just features on my end:
- Could you password protect this function?  Just follow the same procedure as our other routes that are password-protected.
- When you delete the last message of an object, could you remove the entire messages array?  This would be determined by `num` being 1.  Could also add a path that deletes all messages - very easy to adapt the current code and could provide some later benefit.
- When a message is deleted, it is instead replaced by `null`.  Could it be possible to instead remove it from the array?  I think our frontend will crash with message items of `null`.

Hope this is all fine to do - let me know if you have further questions.

**Comment by Sammidysam** [comment]
Also - I see there are pending merge conflicts.  Might want to merge `master` in sooner rather than later and resolve those conflicts.

**Comment by adartulloch** [comment]
Yep, that's all fine to do! One question though, will `num` equaling 1 indicate that it's the last message in the array, or only that the index is 0 (first element in the array)? Couldn't a user want to delete the message at index 0 and keep the remaining messages at other indices?

**Comment by Sammidysam** [comment]
Because of decisions made by the summer programmers who wrote `citywide-dashboard.alpha` last summer, we 1-index gauges (and I think messages accordingly for consistency).  So 1 means index 0.  I completely had a massive error in my writing, as someone could delete the first message without meaning to delete them all.  I guess you would need to check that the messages length is 1, which might involve querying it first, not sure.  Can look into it, I figure.

**Comment by adartulloch** [comment]
Will look into querying for `messages` arrays of length 1.

**Comment by Sammidysam** [comment]
@adartulloch Do you have pending changes or should I finish it up?

**Comment by adartulloch** [comment]
https://stackoverflow.com/questions/48262284/mongodb-remove-element-out-array-with-index
I suppose mongoDB has yet to implement a way to remove an element in an array by index, so combining $unset with $pull seems to be the workaround for it.

**Comment by Sammidysam** [comment]
This task was borderline between being finished off this summer or leaving for later.  Glancing at the code, it looks like there are some reverts of old changes to `master` here, plus some merge conflict headers left in the code, so I think that switches this from a possible easy merge to a more time-involved merge.  As a result, we are going to leave it to the fall.  Definitely I hope no one deletes the branch like the other one, though, as there is plenty of awesome progress here!

**Pull request closed without merging**
